Automattic/vip-quickstart

- bin/wp
`/vagrant` is no longer available. We should be using `/srv` now.
See also ff21c5a67e0e79c9634d2286f7bbae2730249a6d.
> Update wp wrapper to reference /srv/www instead of /vagrant/www

- .gitmodules
FIxes an issue where running `vagrant provision` does not complete, and will not provision in a Windows environment.
> Fix HTTPS clone urls for git submodules: apt & ufw.

- www/wp-content/object-cache.php
When running unit tests for our plugins in Quickstart, we've started getting assertion errors stemming from the object cache unexpectedly having a value set. I figured it could be due to Memcached Object Cache's `WP_Object_Cache::flush()` method doing a short-circuit if it determines that it is running on multisite. So I commented out that condition, re-ran the tests, and they then passed as expected.
The `WP_UnitTestCase::setUp()` method calls a `clean_up_global_scope` method which [flushes the object cache](https://github.com/xwp/wordpress-develop/blob/c67e5da8c9a885aabb5d6dd601394a672f543089/tests/phpunit/includes/testcase.php#L39-L81) to start out with a clean state. This, however, fails on VIP Quickstart because Memcached Object Cache prevents the cache from being flushed.
I'm …
> Remove multisite short-circuit in WP_Object_Cache::flush()

- puppet/files/nginx/vip.dev.erb
Nginx site config: return hard 404 when image/script is not found instead of passing it to php, since doing so might spawn multiple soft 404 requests which is detrimental to performance
> Recommitting lost changes from PR #243

- www/wp-content/mu-plugins/http-concat/cssconcat.php
- www/wp-content/mu-plugins/http-concat/jsconcat.php
I've been noticing Query Monitor reporting issues from `http-concat`:
* Warning: Creating default object from empty value
* Warning: in_array() expects parameter 2 to be array, null given
* Notice: Undefined offset: 2
This PR fixes the issues.
> Fix http-concat warnings & notice

- puppet/manifests/sections/gitplugin.pp
This is required for PR 204 of VIP-Scanner that includes PHP-Parser as a sub-module.
> Make sure we include submodules

- puppet/manifests/sections/wp.pp
- www/wp-config.php
- www/wp-tests/wp-tests-config.php
The default theme is now twentyfifteen. The core unit tests expect this to be the active theme, and they do not run properly otherwise.
> Update default theme to twentyfifteen

- puppet/manifests/sections/wp.pp
This corrects "connection was closed by server" error thrown when fetching over just HTTP
> Fixes #465 - Ensure we pull WP Core and Tests via HTTPS protocol

- puppet/manifests/sections/php.pp
Fix #475 by ensuring `php-pear` is at the latest version (and using the PPA).
> Ensure we're using the latest version of Pear (from the PPA)

- www/wp-config.php
It's been noted by VIP clients that on Quickstart, the Keyring Tools menu page is visible. This is confusing, as there is no such page on WordPress.com VIP.
This is because on VIP, Keyring is in headless mode.
To better mirror production, Quickstart should also put Keyring in headless mode. This PR does that.
> Put Keyring into headless mode, to better match wpcom environment

- puppet/manifests/sections/php.pp
Fix #471 with additional command block to configure PHP CodeSniffer to use WordPress coding standards
> Configure PHP CodeSniffer to use WordPress coding standards

- puppet/manifests/sections/php.pp
- puppet/manifests/sections/wp.pp
This will allow error logs to be writable by default, and allow `WP_DEBUG_LOG` to be used.
To do this we need to:
* Change `php_admin_value[error_log]` and `php_admin_flag[log_errors]` in `/etc/php5/fpm/pool.d/www.conf` to [overridable values](http://php.net/manual/en/configuration.changes.php)
* Create `/var/log/php-fpm-www-error.log` and allow `www-data` to write to it
* Change `/srv/www/wp-content` to allow `www-data` to write to it
> Enable error logging by default

- puppet/manifests/sections/php.pp
This makes the dependency ordering in php.pp less unpredictable and solves #485, I believe. The path to the xdebug.so file won't change too often (we'll just need to make sure it's set if and when the build updates in the PPA). We can't rely on the `php_extension_version` fact defined in https://github.com/jippi/puppet-php/ because it's wrong on first run, and we can't update the default in the fact because that's the *right* build number for the defaults when installing the base debian/ubuntu packages.
> clarify ordering requirements and explicitly set xdebug extension path

- puppet/manifests/sections/database.pp
Occasionally, depending on how the dependency graph shook out, the provisioner would attempt to modify the slow query log setting before mysql was installed. This small fix prevents that.
> ensure mysql has been installed before modifing it

- www/wp-content/mu-plugins/wpcom.php
Avoids mixed content warnings when using Quickstart in a HTTPS environment.
See #50367-z
> Use HTTPS for loading wpcom assets

- .gitmodules
- puppet/manifests/sections/php.pp
This PR isn't prompted by a bug as much as a desire to cut down on the number of actions puppet needs to execute during a reprovisioning. It adds the [puppetlabs-inifile](https://github.com/puppetlabs/puppetlabs-inifile) module so that [puppet-php](https://github.com/jippi/puppet-php) can use Augeas to edit `/etc/php5/fpm/php.ini` and `/etc/php5/fpm/pool.d/www.conf` natively instead of relying on awk and sed being run every time the puppet-php module overwrites their modifications. This means that after the initial provisioning, puppet should stop touching the php settings entirely, and the only updates will be pulling the various wordpress-related repositories up-to-date with their remotes.
> use inifile and Augeas instead of grep and sed for php.ini and fpm config

- www/wp-content/mu-plugins/wpcom.php
is called 'wpcom_intermediate_image_sizes'. Occasionally someone may need to
remove that filter.
Using the same function name makes it possible to remove and re-add the intermediate image sizes filter.
This adjustment makes Quickstart function like production.
Fixes #496.
> Use the function name on VIP that filters out the intermediate image sizes

- www/wp-content/mu-plugins/wpcom.php
On WordPress.com is not possible to have page slugs with a few reserved slugs, neither with Custom Post Types slugs.
This is handled by `wpcom_reserved_page_slugs` function, and this should be included in Quickstart.
> Add `wpcom_reserved_page_slugs`

- puppet/manifests/sections/php.pp
Solves #501. the `exec/file` is lifted pretty much verbatim from the way the puppet module downloads and installs composer.
> PHPCS: switch to installing the phar directly

- www/config/batcache-config.php
Fixes #508 , fatal error caused by code that calls `jetpack_is_mobile`, this change moves the URL specific code inside a check so it doesn't run if we're in a CLI context
> VIP: Fix batcache config breaking WP CLI in some circumstances

- puppet/manifests/sections/php.pp
ref [Zendesk #39914](https://wordpressvip.zendesk.com/requests/39914)
> Bump max_input_vars to 6144 to match WordPress.com

- www/wp-content/mu-plugins/vip.php
On wpcom wpcom_wrap_embeds_in_a_div is run on all embeds. This commit adds the same behaviour to Quickstart
fixes #535 
Zendesk 58983
> Add wpcom_wrap_embeds_in_a_div

- puppet/manifests/sections/php.pp
Currently we're to setting `error_log = /tmp/php-errors` in `/etc/php/7.0/fpm/php.ini` without ensuring that `php7.0-fpm` is actually installed which produces the following error:
> INFO interface: info: err: /Stage[main]//File_line[php error_log]: Could not evaluate: No such file or directory - /etc/php/7.0/fpm/php.ini
This change fixes that.
> Require PHP before configure
